[tools]
# Environments
node = "latest"
'github:nubjs/nub' = "latest"
# Linters & Formatters
hk = 'latest'
stylua = 'latest'
pkl = 'latest'

[deps.nub]
description = 'Automatically install Node.js dependencies via nub.'
sources = ['package.json', 'nub.lock']
outputs = ['node_modules/']
run = 'nub pm pin && nub install'
auto = true

[env]
_.path = ['{{config_root}}/node_modules/.bin']

# See https://github.com/webpro-nl/knip/issues/1813 & https://github.com/oxc-project/oxc/issues/11834
KNIP_DISABLE_RAW_TRANSFER = 1

[task_config.input_groups]
deps = ["package.json", "nub.lock"]
src = ["internal", "tsconfig.*.json"]
check = ["*.js", "*.mjs", "*.cjs", "*.jsx", "*.ts", "*.mts", "*.cts", "*.tsx", "*.vue", "*.json", "*.jsonc", "*.yaml", "*.yml", "*.toml", "*.md", "*.mdc", "*.mdx", "*.lua", "hk.pkl"]
test = ["test"]

[tasks.dev]
run = { task = "check" }

[tasks.build]
run = { task = "check" }

[tasks.start]
run = { task = "check" }

[tasks.check]
description = 'Run all checks.'
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk check {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''
sources = ["@group:deps", "@group:check"]
outputs = []
cache = { enabled = true, command_inputs = ["hk --version"] }

[tasks.fix]
description = 'Fix all check issues.'
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk fix {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''
sources = ["@group:deps", "@group:check"]
outputs = []
cache = { enabled = true, command_inputs = ["hk --version"] }

[tasks.test]
description = "Run tests."
usage = '''
flag "-w --watch" help="Watch files for changes and rerun tests"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
vitest {{ '' if usage.watch else 'run' }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''
sources = ["@group:deps", "@group:src", "@group:test"]
outputs = []
cache = { enabled = true, command_inputs = ["node --version"] }

[tasks.prerelease]
description = 'Prepare for release.'
# All tasks in parallel.
run = { tasks = ["check", "test"] }

[tasks.release]
description = 'Bump the version and push new version of this workflow with a Git tag.'
depends = "prerelease"
run = "bumpp"
raw = true

[tasks.changelog]
description = 'Generate GitHub changelog.'
run = "changelogithub"

[tasks.publish]
description = 'Publish the package.'
run = "nub publish --provenance"

[tasks.publish-commit]
description = 'Publish the committed changes.'
run = "pkg-pr-new publish"
