[env]
_.path = ["./node_modules/.bin"]

[tools]
# Environments
bun = "1.3.14"
aube = "1.22.0"
# Linters & Formatters
hk = "1.48.0"
stylua = "2.5.2"
pkl = "0.31.1"

[deps.bun-aube]
description = "Automatically install dependencies via aube & bun's lockfile."
sources = ["package.json", "bun.lock"]
outputs = ["node_modules/"]
# Because aube's output lockfile has bugs,
# we use `bun install --lockfile-only` to generate a lockfile
run = "bun install --lockfile-only && aube install"
auto = true

[tasks.dev]
run = { task = "check" }

[tasks.build]
run = { task = "check" }

[tasks.start]
run = { task = "check" }

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"

[tasks."test:watch"]
run = "vitest"

[tasks.test]
run = "vitest run"

[tasks.prerelease]
run = { tasks = ["check", "test"] }

[tasks.release]
depends = "prerelease"
run = "bumpp"
raw = true

[tasks.changelog]
run = "changelogithub"

[tasks.publish]
run = [
  "bun pm pack --filename release.tgz",
  "npm publish ./release.tgz --access public --tag latest",
]

[tasks."publish:commit"]
run = "pkg-pr-new publish --bun"
